# Generated by Django 4.1.11 on 2024-04-15 23:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_practicehistory"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserData",
        ),
    ]
