# Generated by Django 4.1.11 on 2024-04-24 01:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_questionnaire"),
    ]

    operations = [
        migrations.AddField(
            model_name="practicelist",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
