# Generated by Django 4.1.11 on 2024-04-24 03:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_practicelist_modified_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="questionnaire",
            old_name="age",
            new_name="birth_year",
        ),
    ]
