# Generated by Django 4.1.11 on 2024-04-29 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_remove_practicelist_user_delete_practicehistory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chathistory",
            name="thread_id",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
